"""Added relationships

Revision ID: 4e2ac7bd9244
Revises: 871171a6dca8
Create Date: 2020-01-23 17:50:43.716965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2ac7bd9244'
down_revision = '871171a6dca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'FETCHES', ['FETCH_ID'], schema='barter')
    op.create_unique_constraint(None, 'GAMES', ['GAME_ID'], schema='barter')
    op.create_unique_constraint(None, 'STATISTICS', ['STAT_ID'], schema='barter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'STATISTICS', schema='barter', type_='unique')
    op.drop_constraint(None, 'GAMES', schema='barter', type_='unique')
    op.drop_constraint(None, 'FETCHES', schema='barter', type_='unique')
    # ### end Alembic commands ###
