"""Initial revision

Revision ID: 871171a6dca8
Revises: 
Create Date: 2020-01-23 15:00:56.183123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871171a6dca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FETCHES',
    sa.Column('FETCH_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FETCH_DATE', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('FETCH_ID'),
    sa.UniqueConstraint('FETCH_ID'),
    schema='barter'
    )
    op.create_table('GAMES',
    sa.Column('GAME_ID', sa.Integer(), nullable=False),
    sa.Column('GAME_TITLE', sa.String(), nullable=False),
    sa.Column('PRICE', sa.Integer(), nullable=True),
    sa.Column('RELEASE_YEAR', sa.Integer(), nullable=True),
    sa.Column('REVIEWS_POSITIVE', sa.Integer(), nullable=True),
    sa.Column('REVIEWS_TOTAL', sa.Integer(), nullable=True),
    sa.Column('ACHIEVEMENTS', sa.Integer(), nullable=True),
    sa.Column('CARDS', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('GAME_ID'),
    sa.UniqueConstraint('GAME_ID'),
    schema='barter'
    )
    op.create_table('STATISTICS',
    sa.Column('STAT_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FETCH_ID', sa.Integer(), nullable=True),
    sa.Column('GAME_ID', sa.Integer(), nullable=True),
    sa.Column('TRADEABLES', sa.Integer(), nullable=True),
    sa.Column('WISHLIST', sa.Integer(), nullable=True),
    sa.Column('LIBRARY', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FETCH_ID'], ['barter.FETCHES.FETCH_ID'], ),
    sa.ForeignKeyConstraint(['GAME_ID'], ['barter.GAMES.GAME_ID'], ),
    sa.PrimaryKeyConstraint('STAT_ID'),
    sa.UniqueConstraint('STAT_ID'),
    schema='barter'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STATISTICS', schema='barter')
    op.drop_table('GAMES', schema='barter')
    op.drop_table('FETCHES', schema='barter')
    # ### end Alembic commands ###
