"""Adding fetches -> statistics relationship

Revision ID: 8f97bf4a60a7
Revises: 4e2ac7bd9244
Create Date: 2020-01-23 17:52:25.345558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f97bf4a60a7'
down_revision = '4e2ac7bd9244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
