"""Added relationship between Fetch and Games

Revision ID: bf8f8efd1868
Revises: 8f97bf4a60a7
Create Date: 2020-01-23 17:53:49.227762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8f8efd1868'
down_revision = '8f97bf4a60a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
