"""Removed relationships

Revision ID: cad041ac17bd
Revises: bf8f8efd1868
Create Date: 2020-01-23 18:02:26.051055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad041ac17bd'
down_revision = 'bf8f8efd1868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
